apiVersion: v1
kind: Namespace
metadata:
  name: inanis
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: inanis
  name: inanis
  namespace: inanis
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/vm: inanis
    spec:
      domain:
        cpu:
          sockets: 1
          cores: 1
          threads: 2
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          interfaces:
          - name: ex-machina-bridge
            bridge: {}
        resources:
          requests:
            memory: 2G
      networks:
      - name: ex-machina-bridge
        multus:
          networkName: ex-machina-uplink
      terminationGracePeriodSeconds: 0
      volumes:
      - name: containerdisk
        containerDisk:
          image: xn--55q89qy6p.com/soph/nixos/inanis:latest
