apiVersion: v1
kind: Namespace
metadata:
  name: conduwuit-namespace

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: conduwuit-pvc
  namespace: conduwuit-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conduwuit-deployment
  namespace: conduwuit-namespace
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: conduwuit
  template:
    metadata:
      labels:
        app: conduwuit
    spec:
      containers:
        - name: conduwuit
          image: docker.io/jevolk/tuwunel:v1.4.2
          ports:
            - containerPort: 6167
          volumeMounts:
            - name: conduwuit-volume
              mountPath: /var/lib/conduwuit
          env:
            - name: CONDUWUIT_SERVER_NAME
              value: "cat.sophiah.gay"
            - name: CONDUWUIT_DATABASE_PATH
              value: "/var/lib/conduwuit"
            - name: CONDUWUIT_PORT
              value: "6167"
            - name: CONDUWUIT_MAX_REQUEST_SIZE
              value: "200000000"
            - name: CONDUWUIT_ALLOW_REGISTRATION
              value: "true"
            - name: CONDUWUIT_REGISTRATION_TOKEN
              value: "GtpePKmUEpfgRGjvx9S98bJoHGLUuBrUgv7MUcMRtxdtwkeAPNm7ihAPCXm4ggXVS6LG9jzaczTt9fpRVCdmxRvepZUyRr5Rk26exu83PkGv7FRTqKnaW7VcUUQdo44q"
            - name: CONDUWUIT_ALLOW_FEDERATION
              value: "true"
            - name: CONDUWUIT_ALLOW_CHECK_FOR_UPDATES
              value: "true"
            - name: CONDUWUIT_TRUSTED_SERVERS
              value: '["matrix.org"]'
            - name: CONDUWUIT_ADDRESS
              value: "0.0.0.0"
      volumes:
        - name: conduwuit-volume
          persistentVolumeClaim:
            claimName: conduwuit-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: conduwuit-service
  namespace: conduwuit-namespace
  annotations:
    metallb.io/loadBalancerIPs: 2a02:810d:6f83:ad00:acab::fafa
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: conduwuit
  ports:
    - protocol: TCP
      port: 6167
      targetPort: 6167
