apiVersion: v1
kind: Namespace
metadata:
  name: conduwuit-namespace

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: conduwuit-pvc
  namespace: conduwuit-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
# Caddy conf
apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
  namespace: conduwuit-namespace
data:
  Caddyfile: |
    cat.sophiah.gay {
      handle /.well-known/matrix/client {
    		respond /.well-known/matrix/client 200 {
    			body "{\"m.server\":{\"base_url\": \"https://cat.sophiah.gay\"},\"m.homeserver\":{\"base_url\": \"https://cat.sophiah.gay\"},\"org.matrix.msc3575.proxy\":{\"url\": \"https://cat.sophiah.gay\"}}"
    			close
    		}
    	}

      handle /.well-known/matrix/server {
        respond /.well-known/matrix/server 200 {
          body "{\"m.server\":\"cat.sophiah.gay:443\"}"
          close
        }
      }

      reverse_proxy localhost:6167
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conduwuit-deployment
  namespace: conduwuit-namespace
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: conduwuit
  template:
    metadata:
      labels:
        app: conduwuit
    spec:
      containers:
        - name: conduwuit
          image: docker.io/jevolk/tuwunel:v1.4.2
          ports:
            - containerPort: 6167
          volumeMounts:
            - name: conduwuit-volume
              mountPath: /var/lib/conduwuit
          env:
            - name: CONDUWUIT_SERVER_NAME
              value: "cat.sophiah.gay"
            - name: CONDUWUIT_DATABASE_PATH
              value: "/var/lib/conduwuit"
            - name: CONDUWUIT_PORT
              value: "6167"
            - name: CONDUWUIT_MAX_REQUEST_SIZE
              value: "200000000"
            - name: CONDUWUIT_ALLOW_REGISTRATION
              value: "true"
            - name: CONDUWUIT_REGISTRATION_TOKEN
              value: "GtpePKmUEpfgRGjvx9S98bJoHGLUuBrUgv7MUcMRtxdtwkeAPNm7ihAPCXm4ggXVS6LG9jzaczTt9fpRVCdmxRvepZUyRr5Rk26exu83PkGv7FRTqKnaW7VcUUQdo44q"
            - name: CONDUWUIT_ALLOW_FEDERATION
              value: "true"
            - name: CONDUWUIT_ALLOW_CHECK_FOR_UPDATES
              value: "true"
            - name: CONDUWUIT_TRUSTED_SERVERS
              value: '["matrix.org"]'
            - name: CONDUWUIT_ADDRESS
              value: "[::]"
        # TODO: Make caddy persist certs
        # Or even better, use kube-cert-manager properly
        - name: caddy-sidecar
          image: docker.io/caddy:2.10.2
          volumeMounts:
            - name: caddy-config
              mountPath: /etc/caddy/Caddyfile
              subPath: Caddyfile
          ports:
            - containerPort: 80
            - containerPort: 443
      volumes:
        - name: conduwuit-volume
          persistentVolumeClaim:
            claimName: conduwuit-pvc
        - name: caddy-config
          configMap:
            name: caddy-config

---
apiVersion: v1
kind: Service
metadata:
  name: conduwuit-service
  namespace: conduwuit-namespace
  annotations:
    kube-vip.io/loadbalancerIPs: 2a02:810d:6f83:ad00:acab::fafa
spec:
  type: LoadBalancer
  # externalTrafficPolicy: Local
  selector:
    app: conduwuit
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 443
      targetPort: 443
      name: https